export const playerList = 
    [
    {
        "key": "0",
        "name": "Joel Embiid",
        "ppg": "30.6",
        "total": 2079,
        "games": 68,
        "team": "Philadelphia 76ers",
        "position": "CF",
        "id": 817081,
        "wikiLink": "https://en.wikipedia.org/wiki/Joel_Embiid",
        "youtubeLink": "https://www.youtube.com/results?search_query=Joel+Embiid+highlights"
    },
    {
        "key": "1",
        "name": "LeBron James",
        "ppg": "30.3",
        "total": 1695,
        "games": 56,
        "team": "Los Angeles Lakers",
        "position": "F",
        "id": 817181,
        "wikiLink": "https://en.wikipedia.org/wiki/LeBron_James",
        "youtubeLink": "https://www.youtube.com/results?search_query=LeBron+James+highlights"
    },
    {
        "key": "2",
        "name": "Giannis Antetokounmpo",
        "ppg": "29.9",
        "total": 2002,
        "games": 67,
        "team": "Milwaukee Bucks",
        "position": "F",
        "id": 816960,
        "wikiLink": "https://en.wikipedia.org/wiki/Giannis_Antetokounmpo",
        "youtubeLink": "https://www.youtube.com/results?search_query=Giannis+Antetokounmpo+highlights"
    },
    {
        "key": "3",
        "name": "Kevin Durant",
        "ppg": "29.9",
        "total": 1643,
        "games": 55,
        "team": "Brooklyn Nets",
        "position": "F",
        "id": 817074,
        "wikiLink": "https://en.wikipedia.org/wiki/Kevin_Durant",
        "youtubeLink": "https://www.youtube.com/results?search_query=Kevin+Durant+highlights"
    },
    {
        "key": "4",
        "name": "Luka Dončić",
        "ppg": "28.4",
        "total": 1847,
        "games": 65,
        "team": "Dallas Mavericks",
        "position": "FG",
        "id": 861608,
        "wikiLink": "https://en.wikipedia.org/wiki/Luka_Dončić",
        "youtubeLink": "https://www.youtube.com/results?search_query=Luka+Dončić+highlights"
    },
    {
        "key": "5",
        "name": "Trae Young",
        "ppg": "28.4",
        "total": 2155,
        "games": 76,
        "team": "Atlanta Hawks",
        "position": "G",
        "id": 940755,
        "wikiLink": "https://en.wikipedia.org/wiki/Trae_Young",
        "youtubeLink": "https://www.youtube.com/results?search_query=Trae+Young+highlights"
    },
    {
        "key": "6",
        "name": "DeMar DeRozan",
        "ppg": "27.9",
        "total": 2118,
        "games": 76,
        "team": "Chicago Bulls",
        "position": "GF",
        "id": 817057,
        "wikiLink": "https://en.wikipedia.org/wiki/DeMar_DeRozan",
        "youtubeLink": "https://www.youtube.com/results?search_query=DeMar+DeRozan+highlights"
    },
    {
        "key": "7",
        "name": "Ja Morant",
        "ppg": "27.4",
        "total": 1564,
        "games": 57,
        "team": "Memphis Grizzlies",
        "position": "G",
        "id": 987102,
        "wikiLink": "https://en.wikipedia.org/wiki/Ja_Morant",
        "youtubeLink": "https://www.youtube.com/results?search_query=Ja+Morant+highlights"
    },
    {
        "key": "8",
        "name": "Nikola Jokic",
        "ppg": "27.1",
        "total": 2004,
        "games": 74,
        "team": "Denver Nuggets",
        "position": "C",
        "id": 817199,
        "wikiLink": "https://en.wikipedia.org/wiki/Nikola_Jokic",
        "youtubeLink": "https://www.youtube.com/results?search_query=Nikola+Jokic+highlights"
    },
    {
        "key": "9",
        "name": "Jayson Tatum",
        "ppg": "26.9",
        "total": 2046,
        "games": 76,
        "team": "Boston Celtics",
        "position": "FG",
        "id": 885203,
        "wikiLink": "https://en.wikipedia.org/wiki/Jayson_Tatum",
        "youtubeLink": "https://www.youtube.com/results?search_query=Jayson+Tatum+highlights"
    },
    {
        "key": "10",
        "name": "Devin Booker",
        "ppg": "26.8",
        "total": 1822,
        "games": 68,
        "team": "Phoenix Suns",
        "position": "G",
        "id": 817000,
        "wikiLink": "https://en.wikipedia.org/wiki/Devin_Booker",
        "youtubeLink": "https://www.youtube.com/results?search_query=Devin+Booker+highlights"
    },
    {
        "key": "11",
        "name": "Donovan Mitchell",
        "ppg": "25.9",
        "total": 1733,
        "games": 67,
        "team": "Utah Jazz",
        "position": "G",
        "id": 885252,
        "wikiLink": "https://en.wikipedia.org/wiki/Donovan_Mitchell",
        "youtubeLink": "https://www.youtube.com/results?search_query=Donovan+Mitchell+highlights"
    },
    {
        "key": "12",
        "name": "Stephen Curry",
        "ppg": "25.5",
        "total": 1630,
        "games": 64,
        "team": "Golden State Warriors",
        "position": "G",
        "id": 817050,
        "wikiLink": "https://en.wikipedia.org/wiki/Stephen_Curry",
        "youtubeLink": "https://www.youtube.com/results?search_query=Stephen+Curry+highlights"
    },
    {
        "key": "13",
        "name": "Karl-Anthony Towns",
        "ppg": "24.6",
        "total": 1818,
        "games": 74,
        "team": "Minnesota Timberwolves",
        "position": "CF",
        "id": 817410,
        "wikiLink": "https://en.wikipedia.org/wiki/Karl-Anthony_Towns",
        "youtubeLink": "https://www.youtube.com/results?search_query=Karl-Anthony+Towns+highlights"
    },
    {
        "key": "14",
        "name": "Shai Gilgeous-Alexander",
        "ppg": "24.5",
        "total": 1371,
        "games": 56,
        "team": "Oklahoma City Thunder",
        "position": "G",
        "id": 940794,
        "wikiLink": "https://en.wikipedia.org/wiki/Shai_Gilgeous-Alexander",
        "youtubeLink": "https://www.youtube.com/results?search_query=Shai+Gilgeous-Alexander+highlights"
    },
    {
        "key": "15",
        "name": "Zach LaVine",
        "ppg": "24.4",
        "total": 1635,
        "games": 67,
        "team": "Chicago Bulls",
        "position": "GF",
        "id": 817218,
        "wikiLink": "https://en.wikipedia.org/wiki/Zach_LaVine",
        "youtubeLink": "https://www.youtube.com/results?search_query=Zach+LaVine+highlights"
    },
    {
        "key": "16",
        "name": "Jaylen Brown",
        "ppg": "23.6",
        "total": 1559,
        "games": 66,
        "team": "Boston Celtics",
        "position": "GF",
        "id": 846898,
        "wikiLink": "https://en.wikipedia.org/wiki/Jaylen_Brown",
        "youtubeLink": "https://www.youtube.com/results?search_query=Jaylen+Brown+highlights"
    },
    {
        "key": "17",
        "name": "De'Aaron Fox",
        "ppg": "23.2",
        "total": 1367,
        "games": 59,
        "team": "Sacramento Kings",
        "position": "G",
        "id": 885244,
        "wikiLink": "https://en.wikipedia.org/wiki/De'Aaron_Fox",
        "youtubeLink": "https://www.youtube.com/results?search_query=De'Aaron+Fox+highlights"
    },
    {
        "key": "18",
        "name": "Pascal Siakam",
        "ppg": "22.8",
        "total": 1551,
        "games": 68,
        "team": "Toronto Raptors",
        "position": "F",
        "id": 846971,
        "wikiLink": "https://en.wikipedia.org/wiki/Pascal_Siakam",
        "youtubeLink": "https://www.youtube.com/results?search_query=Pascal+Siakam+highlights"
    },
    {
        "key": "19",
        "name": "Brandon Ingram",
        "ppg": "22.7",
        "total": 1246,
        "games": 55,
        "team": "New Orleans Pelicans",
        "position": "F",
        "id": 846926,
        "wikiLink": "https://en.wikipedia.org/wiki/Brandon_Ingram",
        "youtubeLink": "https://www.youtube.com/results?search_query=Brandon+Ingram+highlights"
    },
    {
        "key": "20",
        "name": "CJ McCollum",
        "ppg": "22.1",
        "total": 1370,
        "games": 62,
        "team": "New Orleans Pelicans",
        "position": "G",
        "id": 817253,
        "wikiLink": "https://en.wikipedia.org/wiki/CJ_McCollum",
        "youtubeLink": "https://www.youtube.com/results?search_query=CJ+McCollum+highlights"
    },
    {
        "key": "21",
        "name": "James Harden",
        "ppg": "22.0",
        "total": 1432,
        "games": 65,
        "team": "Philadelphia 76ers",
        "position": "G",
        "id": 817133,
        "wikiLink": "https://en.wikipedia.org/wiki/James_Harden",
        "youtubeLink": "https://www.youtube.com/results?search_query=James+Harden+highlights"
    },
    {
        "key": "22",
        "name": "Darius Garland",
        "ppg": "21.7",
        "total": 1473,
        "games": 68,
        "team": "Cleveland Cavaliers",
        "position": "G",
        "id": 987161,
        "wikiLink": "https://en.wikipedia.org/wiki/Darius_Garland",
        "youtubeLink": "https://www.youtube.com/results?search_query=Darius+Garland+highlights"
    },
    {
        "key": "23",
        "name": "Jimmy Butler",
        "ppg": "21.4",
        "total": 1219,
        "games": 57,
        "team": "Miami Heat",
        "position": "F",
        "id": 817017,
        "wikiLink": "https://en.wikipedia.org/wiki/Jimmy_Butler",
        "youtubeLink": "https://www.youtube.com/results?search_query=Jimmy+Butler+highlights"
    },
    {
        "key": "24",
        "name": "Anthony Edwards",
        "ppg": "21.3",
        "total": 1533,
        "games": 72,
        "team": "Minnesota Timberwolves",
        "position": "G",
        "id": 1092929,
        "wikiLink": "https://en.wikipedia.org/wiki/Anthony_Edwards",
        "youtubeLink": "https://www.youtube.com/results?search_query=Anthony+Edwards+highlights"
    },
    {
        "key": "25",
        "name": "Dejounte Murray",
        "ppg": "21.1",
        "total": 1438,
        "games": 68,
        "team": "San Antonio Spurs",
        "position": "G",
        "id": 846964,
        "wikiLink": "https://en.wikipedia.org/wiki/Dejounte_Murray",
        "youtubeLink": "https://www.youtube.com/results?search_query=Dejounte+Murray+highlights"
    },
    {
        "key": "26",
        "name": "Tyler Herro",
        "ppg": "20.7",
        "total": 1367,
        "games": 66,
        "team": "Miami Heat",
        "position": "G",
        "id": 988789,
        "wikiLink": "https://en.wikipedia.org/wiki/Tyler_Herro",
        "youtubeLink": "https://www.youtube.com/results?search_query=Tyler+Herro+highlights"
    },
    {
        "key": "27",
        "name": "Fred VanVleet",
        "ppg": "20.3",
        "total": 1320,
        "games": 65,
        "team": "Toronto Raptors",
        "position": "G",
        "id": 846972,
        "wikiLink": "https://en.wikipedia.org/wiki/Fred_VanVleet",
        "youtubeLink": "https://www.youtube.com/results?search_query=Fred+VanVleet+highlights"
    },
    {
        "key": "28",
        "name": "Kristaps Porzingis",
        "ppg": "20.2",
        "total": 1030,
        "games": 51,
        "team": "Washington Wizards",
        "position": "FC",
        "id": 817330,
        "wikiLink": "https://en.wikipedia.org/wiki/Kristaps_Porzingis",
        "youtubeLink": "https://www.youtube.com/results?search_query=Kristaps+Porzingis+highlights"
    },
    {
        "key": "29",
        "name": "Miles Bridges",
        "ppg": "20.2",
        "total": 1613,
        "games": 80,
        "team": "Charlotte Hornets",
        "position": "F",
        "id": 940806,
        "wikiLink": "https://en.wikipedia.org/wiki/Miles_Bridges",
        "youtubeLink": "https://www.youtube.com/results?search_query=Miles+Bridges+highlights"
    },
    {
        "key": "30",
        "name": "LaMelo Ball",
        "ppg": "20.1",
        "total": 1508,
        "games": 75,
        "team": "Charlotte Hornets",
        "position": "G",
        "id": 1092868,
        "wikiLink": "https://en.wikipedia.org/wiki/LaMelo_Ball",
        "youtubeLink": "https://www.youtube.com/results?search_query=LaMelo+Ball+highlights"
    },
    {
        "key": "31",
        "name": "Julius Randle",
        "ppg": "20.1",
        "total": 1447,
        "games": 72,
        "team": "New York Knicks",
        "position": "FC",
        "id": 817338,
        "wikiLink": "https://en.wikipedia.org/wiki/Julius_Randle",
        "youtubeLink": "https://www.youtube.com/results?search_query=Julius+Randle+highlights"
    },
    {
        "key": "32",
        "name": "Khris Middleton",
        "ppg": "20.1",
        "total": 1325,
        "games": 66,
        "team": "Milwaukee Bucks",
        "position": "F",
        "id": 817265,
        "wikiLink": "https://en.wikipedia.org/wiki/Khris_Middleton",
        "youtubeLink": "https://www.youtube.com/results?search_query=Khris+Middleton+highlights"
    },
    {
        "key": "33",
        "name": "RJ Barrett",
        "ppg": "20.0",
        "total": 1402,
        "games": 70,
        "team": "New York Knicks",
        "position": "FG",
        "id": 988995,
        "wikiLink": "https://en.wikipedia.org/wiki/RJ_Barrett",
        "youtubeLink": "https://www.youtube.com/results?search_query=RJ+Barrett+highlights"
    },
    {
        "key": "34",
        "name": "Terry Rozier",
        "ppg": "19.3",
        "total": 1408,
        "games": 73,
        "team": "Charlotte Hornets",
        "position": "G",
        "id": 817353,
        "wikiLink": "https://en.wikipedia.org/wiki/Terry_Rozier",
        "youtubeLink": "https://www.youtube.com/results?search_query=Terry+Rozier+highlights"
    },
    {
        "key": "35",
        "name": "Jerami Grant",
        "ppg": "19.2",
        "total": 904,
        "games": 47,
        "team": "Detroit Pistons",
        "position": "F",
        "id": 817119,
        "wikiLink": "https://en.wikipedia.org/wiki/Jerami_Grant",
        "youtubeLink": "https://www.youtube.com/results?search_query=Jerami+Grant+highlights"
    },
    {
        "key": "36",
        "name": "Bam Adebayo",
        "ppg": "19.1",
        "total": 1068,
        "games": 56,
        "team": "Miami Heat",
        "position": "CF",
        "id": 885218,
        "wikiLink": "https://en.wikipedia.org/wiki/Bam_Adebayo",
        "youtubeLink": "https://www.youtube.com/results?search_query=Bam+Adebayo+highlights"
    },
    {
        "key": "37",
        "name": "Norman Powell",
        "ppg": "19.0",
        "total": 853,
        "games": 45,
        "team": "Los Angeles Clippers",
        "position": "G",
        "id": 817332,
        "wikiLink": "https://en.wikipedia.org/wiki/Norman_Powell",
        "youtubeLink": "https://www.youtube.com/results?search_query=Norman+Powell+highlights"
    },
    {
        "key": "38",
        "name": "Domantas Sabonis",
        "ppg": "18.9",
        "total": 1171,
        "games": 62,
        "team": "Sacramento Kings",
        "position": "FC",
        "id": 846968,
        "wikiLink": "https://en.wikipedia.org/wiki/Domantas_Sabonis",
        "youtubeLink": "https://www.youtube.com/results?search_query=Domantas+Sabonis+highlights"
    },
    {
        "key": "39",
        "name": "Jordan Poole",
        "ppg": "18.5",
        "total": 1405,
        "games": 76,
        "team": "Golden State Warriors",
        "position": "G",
        "id": 989024,
        "wikiLink": "https://en.wikipedia.org/wiki/Jordan_Poole",
        "youtubeLink": "https://www.youtube.com/results?search_query=Jordan+Poole+highlights"
    },
    {
        "key": "40",
        "name": "Russell Westbrook",
        "ppg": "18.5",
        "total": 1441,
        "games": 78,
        "team": "Los Angeles Lakers",
        "position": "G",
        "id": 817437,
        "wikiLink": "https://en.wikipedia.org/wiki/Russell_Westbrook",
        "youtubeLink": "https://www.youtube.com/results?search_query=Russell+Westbrook+highlights"
    },
    {
        "key": "41",
        "name": "Gary Trent Jr.",
        "ppg": "18.3",
        "total": 1283,
        "games": 70,
        "team": "Toronto Raptors",
        "position": "GF",
        "id": 940761,
        "wikiLink": "https://en.wikipedia.org/wiki/Gary_Trent Jr.",
        "youtubeLink": "https://www.youtube.com/results?search_query=Gary+Trent Jr.+highlights"
    },
    {
        "key": "42",
        "name": "Jrue Holiday",
        "ppg": "18.3",
        "total": 1225,
        "games": 67,
        "team": "Milwaukee Bucks",
        "position": "G",
        "id": 817159,
        "wikiLink": "https://en.wikipedia.org/wiki/Jrue_Holiday",
        "youtubeLink": "https://www.youtube.com/results?search_query=Jrue+Holiday+highlights"
    },
    {
        "key": "43",
        "name": "Desmond Bane",
        "ppg": "18.2",
        "total": 1384,
        "games": 76,
        "team": "Memphis Grizzlies",
        "position": "G",
        "id": 1092872,
        "wikiLink": "https://en.wikipedia.org/wiki/Desmond_Bane",
        "youtubeLink": "https://www.youtube.com/results?search_query=Desmond+Bane+highlights"
    },
    {
        "key": "44",
        "name": "D'Angelo Russell",
        "ppg": "18.1",
        "total": 1176,
        "games": 65,
        "team": "Minnesota Timberwolves",
        "position": "G",
        "id": 817357,
        "wikiLink": "https://en.wikipedia.org/wiki/D'Angelo_Russell",
        "youtubeLink": "https://www.youtube.com/results?search_query=D'Angelo+Russell+highlights"
    },
    {
        "key": "45",
        "name": "Bojan Bogdanović",
        "ppg": "18.1",
        "total": 1248,
        "games": 69,
        "team": "Utah Jazz",
        "position": "F",
        "id": 816997,
        "wikiLink": "https://en.wikipedia.org/wiki/Bojan_Bogdanović",
        "youtubeLink": "https://www.youtube.com/results?search_query=Bojan+Bogdanović+highlights"
    },
    {
        "key": "46",
        "name": "Christian Wood",
        "ppg": "17.9",
        "total": 1218,
        "games": 68,
        "team": "Houston Rockets",
        "position": "F",
        "id": 817455,
        "wikiLink": "https://en.wikipedia.org/wiki/Christian_Wood",
        "youtubeLink": "https://www.youtube.com/results?search_query=Christian+Wood+highlights"
    },
    {
        "key": "47",
        "name": "Jonas Valanciunas",
        "ppg": "17.8",
        "total": 1314,
        "games": 74,
        "team": "New Orleans Pelicans",
        "position": "C",
        "id": 817417,
        "wikiLink": "https://en.wikipedia.org/wiki/Jonas_Valanciunas",
        "youtubeLink": "https://www.youtube.com/results?search_query=Jonas+Valanciunas+highlights"
    },
    {
        "key": "48",
        "name": "Nikola Vučević",
        "ppg": "17.6",
        "total": 1288,
        "games": 73,
        "team": "Chicago Bulls",
        "position": "C",
        "id": 817423,
        "wikiLink": "https://en.wikipedia.org/wiki/Nikola_Vučević",
        "youtubeLink": "https://www.youtube.com/results?search_query=Nikola+Vučević+highlights"
    },
    {
        "key": "49",
        "name": "Tyrese Maxey",
        "ppg": "17.5",
        "total": 1311,
        "games": 75,
        "team": "Philadelphia 76ers",
        "position": "G",
        "id": 1092926,
        "wikiLink": "https://en.wikipedia.org/wiki/Tyrese_Maxey",
        "youtubeLink": "https://www.youtube.com/results?search_query=Tyrese+Maxey+highlights"
    }
]
